### ISSUE TITLE
Can't modify fox2 files upon latest patch

### ISSUE THREAD

**Issue by mxmstr** [Atvaark/TPP.FileFormats#1]
Fox Tool doesn't seem to be working quite right upon the latest patch (1.07.1 I believe). As I was working on my mod yesterday, I noticed that the game would crash after making small changes to f30020.fox2, changes which worked just fine a few days before. 
I then discovered that if I decompiled the fox2 file and then recompiled it without any alterations at all, the game would still crash! On top of that, If I decompile a vanilla fox2 file, then recompile it, and then decompile it again, the resulting XML will be 0kb, with this error in the cmd window:

```
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt64()
   at FoxTool.Fox.FoxHash.Read(Stream input)
   at FoxTool.Fox.FoxStringLookupLiteral.Read(Stream input)
   at FoxTool.Fox.FoxStringLookupLiteral.ReadFoxStringLookupLiteral(Stream input)
   at FoxTool.Fox.FoxFile.Read(Stream input)
   at FoxTool.Fox.FoxFile.ReadFoxFile(Stream input, FoxLookupTable lookupTable)
   at FoxTool.Program.DecompileFile(FileInfo file)
```

Can you look into this? I've gone so far as to reinstall MGS5 entirely and the issue still persists on my end. I really appreciate the time you've taken to make these files moddable, please let me know if this issue happens to you as well. Thanks.

**Comment by Atvaark** [comment]
I'll take a look at this later today. Was the file you mentioned updated in the recent patch?

**Comment by Atvaark** [comment]
I could reproduce it with one of the newer unmodified fox2 files.
[FoxTool v0.2.4](https://github.com/Atvaark/FoxTool/releases/tag/v0.2.4) should fix this issue.

**Comment by mxmstr** [comment]
It works perfectly now, thanks a bunch.
